name: Build and deploy 
on:
#  workflow_run:
#    workflows:
#      - Terraform Apply (Dev)
#    types:
#      - completed
  push:
    branches:
      - main 

    
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  EKS_REPO: project-devops/flask-web
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy: 
    # if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      # configure aws credentials 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      # Login to AWS ECR
      - name: login to aws ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build and push docker image 
      - name: Build and push image 
        working-directory: spring-petclinic 
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID}}.}.dkr.ecr.${AWS_REGION }.}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_TAG 
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV


