name: Build and deploy 
on:
#  workflow_run:
#    workflows:
#      - Terraform Apply (Dev)
#    types:
#      - completed
  push:
    branches:
      - main 

    
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  ECR_REPO: project-devops/flask-web
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy: 
    # if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      # configure aws credentials 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to AWS ECR
      - name: login to aws ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build and push docker image 
      - name: Build and push image 
        uses: docker/build-push-action@v5
        with:
          context: ./spring-petclinic
          push: true 
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ IMAGE_TAG }}



